version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=football_data
      - FOOTBALL_API_TOKEN=your_token_here
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=football_data
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
